// SPDX-License-Identifier: GPL-2.0
/*
 * MediaTek clock driver for MT8192 SoC
 *
 */

#include <dm.h>
#include <asm/io.h>
#include <dt-bindings/clock/mt8192-clk.h>

#include "clk-mtk.h"

#define MT8192_PLL_FMAX		(3800UL * MHZ)
#define MT8192_PLL_FMIN		(1500UL * MHZ)
#define MT8192_INTEGER_BITS 8

#define PLL(_id, _name, _reg, _pwr_reg, _en_mask, _flags,		\
	    _rst_bar_mask, _pcwbits, _pd_reg, _pd_shift,		\
	    _tuner_reg, _tuner_en_reg, _tuner_en_bit,			\
	    _pcw_reg, _pcw_shift, _pcw_chg_reg,				\
	    _en_reg, _pll_en_bit) {					\
		.id = _id,						\
		.reg = _reg,						\
		.pwr_reg = _pwr_reg,					\
		.en_mask = _en_mask,					\
		.rst_bar_mask = _rst_bar_mask,				\
		.fmax = MT8192_PLL_FMAX,				\
		.fmin = MT8192_PLL_FMIN,				\
		.flags = _flags,					\
		.pcwbits = _pcwbits,					\
		.pcwibits = MT8192_INTEGER_BITS,			\
		.pd_reg = _pd_reg,					\
		.pd_shift = _pd_shift,					\
		.pcw_reg = _pcw_reg,					\
		.pcw_shift = _pcw_shift,				\
		.pcw_chg_reg = _pcw_chg_reg,				\
	}

#define PLL_B(_id, _name, _reg, _pwr_reg, _en_mask, _flags,		\
			_rst_bar_mask, _pcwbits, _pd_reg, _pd_shift,	\
			_tuner_reg, _tuner_en_reg, _tuner_en_bit,	\
			_pcw_reg, _pcw_shift)				\
		PLL(_id, _name, _reg, _pwr_reg, _en_mask, _flags,	\
			_rst_bar_mask, _pcwbits, _pd_reg, _pd_shift,	\
			_tuner_reg, _tuner_en_reg, _tuner_en_bit,	\
			_pcw_reg, _pcw_shift, 0, 0, 0)

static const struct mtk_pll_data apmixed_plls[] = {
	PLL_B(CLK_APMIXED_MAINPLL, "mainpll", 0x0340, 0x034c, 0xff000000,
	      HAVE_RST_BAR, BIT(23), 22, 0x0344, 24, 0, 0, 0, 0x0344, 0),
	PLL_B(CLK_APMIXED_UNIVPLL, "univpll", 0x0308, 0x0314, 0xff000000,
	      HAVE_RST_BAR, BIT(23), 22, 0x030c, 24, 0, 0, 0, 0x030c, 0),
	PLL(CLK_APMIXED_USBPLL, "usbpll", 0x03c4, 0x03cc, 0x00000000,
	    0, 0, 22, 0x03c4, 24, 0, 0, 0, 0x03c4, 0, 0x03c4, 0x03cc, 2),
	PLL_B(CLK_APMIXED_MSDCPLL, "msdcpll", 0x0350, 0x035c, 0x00000000,
	      0, 0, 22, 0x0354, 24, 0, 0, 0, 0x0354, 0),
	PLL_B(CLK_APMIXED_MMPLL, "mmpll", 0x0360, 0x036c, 0xff000000,
	      HAVE_RST_BAR, BIT(23), 22, 0x0364, 24, 0, 0, 0, 0x0364, 0),
	PLL_B(CLK_APMIXED_ADSPPLL, "adsppll", 0x0370, 0x037c, 0xff000000,
	      HAVE_RST_BAR, BIT(23), 22, 0x0374, 24, 0, 0, 0, 0x0374, 0),
	PLL_B(CLK_APMIXED_MFGPLL, "mfgpll", 0x0268, 0x0274, 0x00000000,
	      0, 0, 22, 0x026c, 24, 0, 0, 0, 0x026c, 0),
	PLL_B(CLK_APMIXED_TVDPLL, "tvdpll", 0x0380, 0x038c, 0x00000000,
	      0, 0, 22, 0x0384, 24, 0, 0, 0, 0x0384, 0),
	PLL_B(CLK_APMIXED_APLL1, "apll1", 0x0318, 0x0328, 0x00000000,
	      0, 0, 32, 0x031c, 24, 0x0040, 0x000c, 0, 0x0320, 0),
	PLL_B(CLK_APMIXED_APLL2, "apll2", 0x032c, 0x033c, 0x00000000,
	      0, 0, 32, 0x0330, 24, 0, 0, 0, 0x0334, 0),
};

static const struct mtk_fixed_clk top_fixed_clks[] = {
	FIXED_CLK(CLK_TOP_ULPOSC, 0, 260000000),
	FIXED_CLK(CLK_TOP_CLK26M, CLK_XTAL, 26000000),
};

static const struct mtk_fixed_factor top_fixed_divs[] = {
	FACTOR(CLK_TOP_MAINPLL_D3, CLK_APMIXED_MAINPLL, 1, 3, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D4, CLK_APMIXED_MAINPLL, 1, 4, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D4_D2, CLK_TOP_MAINPLL_D4, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D4_D4, CLK_TOP_MAINPLL_D4, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D4_D8, CLK_TOP_MAINPLL_D4, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D4_D16, CLK_TOP_MAINPLL_D4, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D5, CLK_APMIXED_MAINPLL, 1, 5, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D5_D2, CLK_TOP_MAINPLL_D5, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D5_D4, CLK_TOP_MAINPLL_D5, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D5_D8, CLK_TOP_MAINPLL_D5, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D6, CLK_APMIXED_MAINPLL, 1, 6, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D6_D2, CLK_TOP_MAINPLL_D6, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D6_D4, CLK_TOP_MAINPLL_D6, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D7, CLK_APMIXED_MAINPLL, 1, 7, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D7_D2, CLK_TOP_MAINPLL_D7, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D7_D4, CLK_TOP_MAINPLL_D7, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D7_D8, CLK_TOP_MAINPLL_D7, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D3, CLK_APMIXED_UNIVPLL, 1, 3, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_D4, CLK_APMIXED_UNIVPLL, 1, 4, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_D4_D2, CLK_TOP_UNIVPLL_D4, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D4_D4, CLK_TOP_UNIVPLL_D4, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D4_D8, CLK_TOP_UNIVPLL_D4, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D5, CLK_APMIXED_UNIVPLL, 1, 5, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_D5_D2, CLK_TOP_UNIVPLL_D5, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D5_D4, CLK_TOP_UNIVPLL_D5, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D5_D8, CLK_TOP_UNIVPLL_D5, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D6, CLK_APMIXED_UNIVPLL, 1, 6, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_D6_D2, CLK_TOP_UNIVPLL_D6, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D6_D4, CLK_TOP_UNIVPLL_D6, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D6_D8, CLK_TOP_UNIVPLL_D6, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D6_D16, CLK_TOP_UNIVPLL_D6, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D7, CLK_APMIXED_UNIVPLL, 1, 7, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL1, CLK_APMIXED_APLL1, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL1_D2, CLK_TOP_APLL1, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_APLL1_D4, CLK_TOP_APLL1, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_APLL1_D8, CLK_TOP_APLL1, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_APLL2, CLK_APMIXED_APLL2, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL2_D2, CLK_TOP_APLL2, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_APLL2_D4, CLK_TOP_APLL2, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_APLL2_D8, CLK_TOP_APLL2, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MMPLL_D4, CLK_APMIXED_MMPLL, 1, 4, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MMPLL_D4_D2, CLK_TOP_MMPLL_D4, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MMPLL_D5, CLK_APMIXED_MMPLL, 1, 5, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MMPLL_D5_D2, CLK_TOP_MMPLL_D5, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MMPLL_D6, CLK_APMIXED_MMPLL, 1, 6, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MMPLL_D6_D2, CLK_TOP_MMPLL_D6, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MMPLL_D7, CLK_APMIXED_MMPLL, 1, 7, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MMPLL_D9, CLK_APMIXED_MMPLL, 1, 9, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_TVDPLL, CLK_APMIXED_TVDPLL, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_TVDPLL_D2, CLK_TOP_TVDPLL, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_TVDPLL_D4, CLK_TOP_TVDPLL, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_TVDPLL_D8, CLK_TOP_TVDPLL, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_TVDPLL_D16, CLK_TOP_TVDPLL, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MSDCPLL, CLK_APMIXED_MSDCPLL, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MSDCPLL_D2, CLK_TOP_MSDCPLL, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MSDCPLL_D4, CLK_TOP_MSDCPLL, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D2, CLK_TOP_ULPOSC, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D4, CLK_TOP_ULPOSC, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D8, CLK_TOP_ULPOSC, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D10, CLK_TOP_ULPOSC, 1, 10, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D16, CLK_TOP_ULPOSC, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_OSC_D20, CLK_TOP_ULPOSC, 1, 20, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_CSW_F26M_D2, CLK_TOP_CLK26M, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_ADSPPLL, CLK_APMIXED_ADSPPLL, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_192M, CLK_APMIXED_UNIVPLL, 1, 13, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_192M_D2, CLK_TOP_UNIVPLL_192M, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_192M_D4, CLK_TOP_UNIVPLL_192M, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_192M_D8, CLK_TOP_UNIVPLL_192M, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_192M_D16, CLK_TOP_UNIVPLL_192M, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_192M_D32, CLK_TOP_UNIVPLL_192M, 1, 32, CLK_PARENT_TOPCKGEN),
};

static const int axi_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_MAINPLL_D7_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_OSC_D4
};

static const int spm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_OSC_D10,
	CLK_TOP_MAINPLL_D7_D4,
	CLK_TOP_CLK32K
};

static const int scp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_UNIVPLL_D4_D2
};

static const int bus_aximem_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D7_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MAINPLL_D6
};

static const int disp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_UNIVPLL_D5_D2,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MMPLL_D5_D2
};

static const int mdp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MMPLL_D4_D2,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_TVDPLL,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_MMPLL_D5_D2
};

static const int img_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_TVDPLL,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MMPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_MMPLL_D5_D2
};

static const int ipe_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_MMPLL_D5_D2
};

static const int dpe_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_UNIVPLL_D5_D2,
	CLK_TOP_MMPLL_D6_D2
};

static const int cam_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_UNIVPLL_D6_D2
};

static const int ccu_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_MMPLL_D5_D2,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_UNIVPLL_D6_D2
};

static const int dsp7_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_MMPLL_D5,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_MMPLL_D4
};

static const int mfg_ref_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MAINPLL_D5_D2
};

static const int mfg_pll_parents[] = {
	CLK_TOP_MFG_REF_SEL,
	CLK_TOP_MFGPLL
};

static const int camtg_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_192M_D8,
	CLK_TOP_UNIVPLL_D6_D8,
	CLK_TOP_UNIVPLL_192M_D4,
	CLK_TOP_UNIVPLL_D6_D16,
	CLK_TOP_CSW_F26M_D2,
	CLK_TOP_UNIVPLL_192M_D16,
	CLK_TOP_UNIVPLL_192M_D32
};

static const int uart_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D6_D8
};

static const int spi_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D4,
	CLK_TOP_MAINPLL_D6_D4,
	CLK_TOP_MSDCPLL_D4
};

static const int msdc50_0_h_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D6_D2
};

static const int msdc50_0_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MSDCPLL,
	CLK_TOP_MSDCPLL_D2,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_UNIVPLL_D4_D2
};

static const int msdc30_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MAINPLL_D7_D2,
	CLK_TOP_MSDCPLL_D2
};

static const int audio_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D8,
	CLK_TOP_MAINPLL_D7_D8,
	CLK_TOP_MAINPLL_D4_D16
};

static const int aud_intbus_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_MAINPLL_D7_D4
};

static const int pwrap_ulposc_parents[] = {
	CLK_TOP_OSC_D10,
	CLK_TOP_CLK26M,
	CLK_TOP_OSC_D4,
	CLK_TOP_OSC_D8,
	CLK_TOP_OSC_D16
};

static const int atb_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D5_D2
};

static const int dpi_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_TVDPLL_D2,
	CLK_TOP_TVDPLL_D4,
	CLK_TOP_TVDPLL_D8,
	CLK_TOP_TVDPLL_D16
};

static const int scam_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D4
};

static const int disp_pwm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D6_D4,
	CLK_TOP_OSC_D2,
	CLK_TOP_OSC_D4,
	CLK_TOP_OSC_D16
};

static const int usb_top_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_UNIVPLL_D6_D4,
	CLK_TOP_UNIVPLL_D5_D2
};

static const int ssusb_xhci_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_UNIVPLL_D6_D4,
	CLK_TOP_UNIVPLL_D5_D2
};

static const int i2c_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D8,
	CLK_TOP_UNIVPLL_D5_D4
};

static const int seninf_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_UNIVPLL_D7,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D5
};

static const int tl_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_192M_D2,
	CLK_TOP_MAINPLL_D6_D4
};

static const int dxcc_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_MAINPLL_D4_D8
};

static const int aud_engen1_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL1_D2,
	CLK_TOP_APLL1_D4,
	CLK_TOP_APLL1_D8
};

static const int aud_engen2_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL2_D2,
	CLK_TOP_APLL2_D4,
	CLK_TOP_APLL2_D8
};

static const int aes_ufsfde_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_UNIVPLL_D6
};

static const int ufs_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_MAINPLL_D4_D8,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MSDCPLL_D2
};

static const int aud_1_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL1
};

static const int aud_2_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL2
};

static const int adsp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_ULPOSC,
	CLK_TOP_ADSPPLL
};

static const int dpmaif_main_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_UNIVPLL_D4_D2
};

static const int venc_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_UNIVPLL_D6,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MAINPLL_D6_D2,
	CLK_TOP_MMPLL_D9,
	CLK_TOP_UNIVPLL_D4_D4,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_UNIVPLL_D5_D2,
	CLK_TOP_MAINPLL_D5
};

static const int vdec_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_192M_D2,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_MAINPLL_D5,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MMPLL_D6_D2,
	CLK_TOP_UNIVPLL_D5_D2,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_UNIVPLL_D7,
	CLK_TOP_MMPLL_D7,
	CLK_TOP_MMPLL_D6,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_MAINPLL_D4,
	CLK_TOP_UNIVPLL_D4,
	CLK_TOP_UNIVPLL_D6
};

static const int camtm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D7,
	CLK_TOP_UNIVPLL_D6_D2,
	CLK_TOP_UNIVPLL_D4_D2
};

static const int pwm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D4_D8
};

static const int audio_h_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D7,
	CLK_TOP_APLL1,
	CLK_TOP_APLL2
};

static const int spmi_mst_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_CSW_F26M_D2,
	CLK_TOP_OSC_D8,
	CLK_TOP_OSC_D10,
	CLK_TOP_OSC_D16,
	CLK_TOP_OSC_D20,
	CLK_TOP_CLK32K
};

static const int aes_msdcfde_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D4_D2,
	CLK_TOP_MAINPLL_D6,
	CLK_TOP_MAINPLL_D4_D4,
	CLK_TOP_UNIVPLL_D4_D2,
	CLK_TOP_UNIVPLL_D6
};

static const int sflash_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D7_D8,
	CLK_TOP_UNIVPLL_D6_D8,
	CLK_TOP_UNIVPLL_D5_D8
};

static const struct mtk_composite top_muxes[] = {
	/* CLK_CFG_0 */
	MUX_GATE(CLK_TOP_AXI_SEL, axi_parents, 0x010, 0, 3, 7),
	MUX_GATE(CLK_TOP_SPM_SEL, spm_parents, 0x010, 8, 2, 15),
	MUX_GATE(CLK_TOP_SCP_SEL, scp_parents, 0x010, 16, 3, 23),
	MUX_GATE(CLK_TOP_BUS_AXIMEM_SEL, bus_aximem_parents, 0x010, 24, 3, 31),
	/* CLK_CFG_1 */
	MUX_GATE(CLK_TOP_DISP_SEL, disp_parents, 0x020, 0, 4, 7),
	MUX_GATE(CLK_TOP_MDP_SEL, mdp_parents, 0x020, 8, 4, 15),
	MUX_GATE(CLK_TOP_IMG1_SEL, img_parents, 0x020, 16, 4, 23),
	MUX_GATE(CLK_TOP_IMG2_SEL, img_parents, 0x020, 24, 4, 31),
	/* CLK_CFG_2 */
	MUX_GATE(CLK_TOP_IPE_SEL, ipe_parents, 0x030, 0, 4, 7),
	MUX_GATE(CLK_TOP_DPE_SEL, dpe_parents, 0x030, 8, 3, 15),
	MUX_GATE(CLK_TOP_CAM_SEL, cam_parents, 0x030, 16, 4, 23),
	MUX_GATE(CLK_TOP_CCU_SEL, ccu_parents, 0x030, 24, 4, 31),
	/* CLK_CFG_4 */
	MUX_GATE(CLK_TOP_DSP7_SEL, dsp7_parents, 0x050, 0, 3, 7),
	MUX_GATE(CLK_TOP_MFG_REF_SEL, mfg_ref_parents, 0x050, 16, 2, 23),
	MUX_GATE(CLK_TOP_MFG_PLL_SEL, mfg_pll_parents, 0x050, 18, 1, -1),
	MUX_GATE(CLK_TOP_CAMTG_SEL, camtg_parents, 0x050, 24, 3, 31),
	/* CLK_CFG_5 */
	MUX_GATE(CLK_TOP_CAMTG2_SEL, camtg_parents, 0x060, 0, 3, 7),
	MUX_GATE(CLK_TOP_CAMTG3_SEL, camtg_parents, 0x060, 8, 3, 15),
	MUX_GATE(CLK_TOP_CAMTG4_SEL, camtg_parents, 0x060, 16, 3, 23),
	MUX_GATE(CLK_TOP_CAMTG5_SEL, camtg_parents, 0x060, 24, 3, 31),
	/* CLK_CFG_6 */
	MUX_GATE(CLK_TOP_CAMTG6_SEL, camtg_parents, 0x070, 0, 3, 7),
	MUX_GATE(CLK_TOP_UART_SEL, uart_parents, 0x070, 8, 1, 15),
	MUX_GATE(CLK_TOP_SPI_SEL, spi_parents, 0x070, 16, 2, 23),
	MUX_GATE(CLK_TOP_MSDC50_0_H_SEL, msdc50_0_h_parents, 0x070, 24, 2, 31),
	/* CLK_CFG_7 */
	MUX_GATE(CLK_TOP_MSDC50_0_SEL, msdc50_0_parents, 0x080, 0, 3, 7),
	MUX_GATE(CLK_TOP_MSDC30_1_SEL, msdc30_parents, 0x080, 8, 3, 15),
	MUX_GATE(CLK_TOP_MSDC30_2_SEL, msdc30_parents, 0x080, 16, 3, 23),
	MUX_GATE(CLK_TOP_AUDIO_SEL, audio_parents, 0x080, 24, 2, 31),
	/* CLK_CFG_8 */
	MUX_GATE(CLK_TOP_AUD_INTBUS_SEL, aud_intbus_parents, 0x090, 0, 2, 7),
	MUX_GATE(CLK_TOP_PWRAP_ULPOSC_SEL, pwrap_ulposc_parents, 0x090, 8, 3, 15),
	MUX_GATE(CLK_TOP_ATB_SEL, atb_parents, 0x090, 16, 2, 23),
	/* CLK_CFG_9 */
	MUX_GATE(CLK_TOP_DPI_SEL, dpi_parents, 0x0a0, 0, 3, 7),
	MUX_GATE(CLK_TOP_SCAM_SEL, scam_parents, 0x0a0, 8, 1, 15),
	MUX_GATE(CLK_TOP_DISP_PWM_SEL, disp_pwm_parents, 0x0a0, 16, 3, 23),
	MUX_GATE(CLK_TOP_USB_TOP_SEL, usb_top_parents, 0x0a0, 24, 2, 31),
	/* CLK_CFG_10 */
	MUX_GATE(CLK_TOP_SSUSB_XHCI_SEL, ssusb_xhci_parents, 0x0b0, 0, 2, 7),
	MUX_GATE(CLK_TOP_I2C_SEL, i2c_parents, 0x0b0, 8, 2, 15),
	MUX_GATE(CLK_TOP_SENINF_SEL, seninf_parents, 0x0b0, 16, 3, 23),
	MUX_GATE(CLK_TOP_SENINF1_SEL, seninf_parents, 0x0b0, 24, 3, 31),
	/* CLK_CFG_11 */
	MUX_GATE(CLK_TOP_SENINF2_SEL, seninf_parents, 0x0c0, 0, 3, 7),
	MUX_GATE(CLK_TOP_SENINF3_SEL, seninf_parents, 0x0c0, 8, 3, 15),
	MUX_GATE(CLK_TOP_TL_SEL, tl_parents, 0x0c0, 16, 2, 23),
	MUX_GATE(CLK_TOP_DXCC_SEL, dxcc_parents, 0x0c0, 24, 2, 31),
	/* CLK_CFG_12 */
	MUX_GATE(CLK_TOP_AUD_ENGEN1_SEL, aud_engen1_parents, 0x0d0, 0, 2, 7),
	MUX_GATE(CLK_TOP_AUD_ENGEN2_SEL, aud_engen2_parents, 0x0d0, 8, 2, 15),
	MUX_GATE(CLK_TOP_AES_UFSFDE_SEL, aes_ufsfde_parents, 0x0d0, 16, 3, 23),
	MUX_GATE(CLK_TOP_UFS_SEL, ufs_parents, 0x0d0, 24, 3, 31),
	/* CLK_CFG_13 */
	MUX_GATE(CLK_TOP_AUD_1_SEL, aud_1_parents, 0x0e0, 0, 1, 7),
	MUX_GATE(CLK_TOP_AUD_2_SEL, aud_2_parents, 0x0e0, 8, 1, 15),
	MUX_GATE(CLK_TOP_ADSP_SEL, adsp_parents, 0x0e0, 16, 3, 23),
	MUX_GATE(CLK_TOP_DPMAIF_MAIN_SEL, dpmaif_main_parents, 0x0e0, 24, 3, 31),
	/* CLK_CFG_14 */
	MUX_GATE(CLK_TOP_VENC_SEL, venc_parents, 0x0f0, 0, 4, 7),
	MUX_GATE(CLK_TOP_VDEC_SEL, vdec_parents, 0x0f0, 8, 4, 15),
	MUX_GATE(CLK_TOP_CAMTM_SEL, camtm_parents, 0x0f0, 16, 2, 23),
	MUX_GATE(CLK_TOP_PWM_SEL, pwm_parents, 0x0f0, 24, 1, 31),
	/* CLK_CFG_15 */
	MUX_GATE(CLK_TOP_AUDIO_H_SEL, audio_h_parents, 0x100, 0, 2, 7),
	MUX_GATE(CLK_TOP_SPMI_MST_SEL, spmi_mst_parents, 0x100, 8, 3, 15),
	MUX_GATE(CLK_TOP_AES_MSDCFDE_SEL, aes_msdcfde_parents, 0x100, 24, 3, 31),
	/* CLK_CFG_16 */
	MUX_GATE(CLK_TOP_SFLASH_SEL, sflash_parents, 0x110, 8, 2, 15),
};

const struct mtk_clk_tree mt8192_clk_tree = {
	.xtal_rate = 26 * MHZ,
	.xtal2_rate = 26 * MHZ,
	.fdivs_offs = CLK_TOP_MAINPLL_D3,
	.muxes_offs = CLK_TOP_AXI_SEL,
	.plls = apmixed_plls,
	.fclks = top_fixed_clks,
	.fdivs = top_fixed_divs,
	.muxes = top_muxes,
};

static const struct mtk_gate_regs infra0_cg_regs = {
	.set_ofs = 0x80,
	.clr_ofs = 0x84,
	.sta_ofs = 0x90,
};

static const struct mtk_gate_regs infra1_cg_regs = {
	.set_ofs = 0x88,
	.clr_ofs = 0x8c,
	.sta_ofs = 0x94,
};

static const struct mtk_gate_regs infra2_cg_regs = {
	.set_ofs = 0xa4,
	.clr_ofs = 0xa8,
	.sta_ofs = 0xac,
};

static const struct mtk_gate_regs infra3_cg_regs = {
	.set_ofs = 0xc0,
	.clr_ofs = 0xc4,
	.sta_ofs = 0xc8,
};

static const struct mtk_gate_regs infra4_cg_regs = {
	.set_ofs = 0xd0,
	.clr_ofs = 0xd4,
	.sta_ofs = 0xd8,
};

static const struct mtk_gate_regs infra5_cg_regs = {
	.set_ofs = 0xe0,
	.clr_ofs = 0xe4,
	.sta_ofs = 0xe8,
};

#define GATE_INFRA0(_id, _parent, _shift)	\
	GATE_MTK_FLAGS(_id, _parent, &infra0_cg_regs, _shift, \
	CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

#define GATE_INFRA1(_id, _parent, _shift)	\
	GATE_MTK_FLAGS(_id, _parent, &infra1_cg_regs, _shift, \
	CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

#define GATE_INFRA2(_id, _parent, _shift)	\
	GATE_MTK_FLAGS(_id, _parent, &infra2_cg_regs, _shift, \
	CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

#define GATE_INFRA3(_id, _parent, _shift)	\
	GATE_MTK_FLAGS(_id, _parent, &infra3_cg_regs, _shift, \
	CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

#define GATE_INFRA4(_id, _parent, _shift)	\
	GATE_MTK_FLAGS(_id, _parent, &infra4_cg_regs, _shift, \
	CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

#define GATE_INFRA5(_id, _parent, _shift)	\
	GATE_MTK_FLAGS(_id, _parent, &infra5_cg_regs, _shift, \
	CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

static const struct mtk_gate infra_clks[] = {
	/* INFRA0 */
	GATE_INFRA0(CLK_INFRA_PMIC_TMR, CLK_TOP_PWRAP_ULPOSC_SEL, 0),
	GATE_INFRA0(CLK_INFRA_PMIC_AP, CLK_TOP_PWRAP_ULPOSC_SEL, 1),
	GATE_INFRA0(CLK_INFRA_PMIC_MD, CLK_TOP_PWRAP_ULPOSC_SEL, 2),
	GATE_INFRA0(CLK_INFRA_PMIC_CONN, CLK_TOP_PWRAP_ULPOSC_SEL, 3),
	GATE_INFRA0(CLK_INFRA_SCPSYS, CLK_TOP_SCP_SEL, 4),
	GATE_INFRA0(CLK_INFRA_SEJ, CLK_TOP_AXI_SEL, 5),
	GATE_INFRA0(CLK_INFRA_APXGPT, CLK_TOP_AXI_SEL, 6),
	GATE_INFRA0(CLK_INFRA_GCE, CLK_TOP_AXI_SEL, 8),
	GATE_INFRA0(CLK_INFRA_GCE2, CLK_TOP_AXI_SEL, 9),
	GATE_INFRA0(CLK_INFRA_THERM, CLK_TOP_AXI_SEL, 10),
	GATE_INFRA0(CLK_INFRA_I2C0, CLK_TOP_I2C_SEL, 11),
	GATE_INFRA0(CLK_INFRA_AP_DMA_PSEUDO, CLK_TOP_AXI_SEL, 12),
	GATE_INFRA0(CLK_INFRA_I2C2, CLK_TOP_I2C_SEL, 13),
	GATE_INFRA0(CLK_INFRA_I2C3, CLK_TOP_I2C_SEL, 14),
	GATE_INFRA0(CLK_INFRA_PWM_H, CLK_TOP_AXI_SEL, 15),
	GATE_INFRA0(CLK_INFRA_PWM1, CLK_TOP_PWM_SEL, 16),
	GATE_INFRA0(CLK_INFRA_PWM2, CLK_TOP_PWM_SEL, 17),
	GATE_INFRA0(CLK_INFRA_PWM3, CLK_TOP_PWM_SEL, 18),
	GATE_INFRA0(CLK_INFRA_PWM4, CLK_TOP_PWM_SEL, 19),
	GATE_INFRA0(CLK_INFRA_PWM, CLK_TOP_PWM_SEL, 21),
	GATE_INFRA0(CLK_INFRA_UART0, CLK_TOP_UART_SEL, 22),
	GATE_INFRA0(CLK_INFRA_UART1, CLK_TOP_UART_SEL, 23),
	GATE_INFRA0(CLK_INFRA_UART2, CLK_TOP_UART_SEL, 24),
	GATE_INFRA0(CLK_INFRA_UART3, CLK_TOP_UART_SEL, 25),
	GATE_INFRA0(CLK_INFRA_GCE_26M, CLK_TOP_AXI_SEL, 27),
	GATE_INFRA0(CLK_INFRA_CQ_DMA_FPC, CLK_TOP_AXI_SEL, 28),
	GATE_INFRA0(CLK_INFRA_BTIF, CLK_TOP_AXI_SEL, 31),
	/* INFRA1 */
	GATE_INFRA1(CLK_INFRA_SPI0, CLK_TOP_SPI_SEL, 1),
	GATE_INFRA1(CLK_INFRA_MSDC0, CLK_TOP_MSDC50_0_H_SEL, 2),
	GATE_INFRA1(CLK_INFRA_MSDC1, CLK_TOP_MSDC50_0_H_SEL, 4),
	GATE_INFRA1(CLK_INFRA_MSDC2, CLK_TOP_MSDC50_0_H_SEL, 5),
	GATE_INFRA1(CLK_INFRA_MSDC0_SRC, CLK_TOP_MSDC50_0_SEL, 6),
	GATE_INFRA1(CLK_INFRA_GCPU, CLK_TOP_AXI_SEL, 8),
	GATE_INFRA1(CLK_INFRA_TRNG, CLK_TOP_AXI_SEL, 9),
	GATE_INFRA1(CLK_INFRA_AUXADC, CLK_TOP_CLK26M, 10),
	GATE_INFRA1(CLK_INFRA_CPUM, CLK_TOP_AXI_SEL, 11),
	GATE_INFRA1(CLK_INFRA_CCIF1_AP, CLK_TOP_AXI_SEL, 12),
	GATE_INFRA1(CLK_INFRA_CCIF1_MD, CLK_TOP_AXI_SEL, 13),
	GATE_INFRA1(CLK_INFRA_AUXADC_MD, CLK_TOP_CLK26M, 14),
	GATE_INFRA1(CLK_INFRA_PCIE_TL_26M, CLK_TOP_AXI_SEL, 15),
	GATE_INFRA1(CLK_INFRA_MSDC1_SRC, CLK_TOP_MSDC30_1_SEL, 16),
	GATE_INFRA1(CLK_INFRA_MSDC2_SRC, CLK_TOP_MSDC30_2_SEL, 17),
	GATE_INFRA1(CLK_INFRA_PCIE_TL_96M, CLK_TOP_TL_SEL, 18),
	GATE_INFRA1(CLK_INFRA_PCIE_PL_P_250M, CLK_TOP_AXI_SEL, 19),
	GATE_INFRA1(CLK_INFRA_DEVICE_APC, CLK_TOP_AXI_SEL, 20),
	GATE_INFRA1(CLK_INFRA_CCIF_AP, CLK_TOP_AXI_SEL, 23),
	GATE_INFRA1(CLK_INFRA_DEBUGSYS, CLK_TOP_AXI_SEL, 24),
	GATE_INFRA1(CLK_INFRA_AUDIO, CLK_TOP_AXI_SEL, 25),
	GATE_INFRA1(CLK_INFRA_CCIF_MD, CLK_TOP_AXI_SEL, 26),
	GATE_INFRA1(CLK_INFRA_DXCC_SEC_CORE, CLK_TOP_DXCC_SEL, 27),
	GATE_INFRA1(CLK_INFRA_DXCC_AO, CLK_TOP_DXCC_SEL, 28),
	GATE_INFRA1(CLK_INFRA_DBG_TRACE, CLK_TOP_AXI_SEL, 29),
	GATE_INFRA1(CLK_INFRA_DEVMPU_B, CLK_TOP_AXI_SEL, 30),
	GATE_INFRA1(CLK_INFRA_DRAMC_F26M, CLK_TOP_CLK26M, 31),
	/* INFRA2 */
	GATE_INFRA2(CLK_INFRA_IRTX, CLK_TOP_CLK26M, 0),
	GATE_INFRA2(CLK_INFRA_SSUSB, CLK_TOP_USB_TOP_SEL, 1),
	GATE_INFRA2(CLK_INFRA_DISP_PWM, CLK_TOP_AXI_SEL, 2),
	GATE_INFRA2(CLK_INFRA_CLDMA_B, CLK_TOP_AXI_SEL, 3),
	GATE_INFRA2(CLK_INFRA_AUDIO_26M_B, CLK_TOP_CLK26M, 4),
	GATE_INFRA2(CLK_INFRA_MODEM_TEMP_SHARE, CLK_TOP_CLK26M, 5),
	GATE_INFRA2(CLK_INFRA_SPI1, CLK_TOP_SPI_SEL, 6),
	GATE_INFRA2(CLK_INFRA_I2C4, CLK_TOP_I2C_SEL, 7),
	GATE_INFRA2(CLK_INFRA_SPI2, CLK_TOP_SPI_SEL, 9),
	GATE_INFRA2(CLK_INFRA_SPI3, CLK_TOP_SPI_SEL, 10),
	GATE_INFRA2(CLK_INFRA_UNIPRO_SYS, CLK_TOP_UFS_SEL, 11),
	GATE_INFRA2(CLK_INFRA_UNIPRO_TICK, CLK_TOP_CLK26M, 12),
	GATE_INFRA2(CLK_INFRA_UFS_MP_SAP_B, CLK_TOP_CLK26M, 13),
	GATE_INFRA2(CLK_INFRA_MD32_B, CLK_TOP_AXI_SEL, 14),
	GATE_INFRA2(CLK_INFRA_UNIPRO_MBIST, CLK_TOP_AXI_SEL, 16),
	GATE_INFRA2(CLK_INFRA_I2C5, CLK_TOP_I2C_SEL, 18),
	GATE_INFRA2(CLK_INFRA_I2C5_ARBITER, CLK_TOP_I2C_SEL, 19),
	GATE_INFRA2(CLK_INFRA_I2C5_IMM, CLK_TOP_I2C_SEL, 20),
	GATE_INFRA2(CLK_INFRA_I2C1_ARBITER, CLK_TOP_I2C_SEL, 21),
	GATE_INFRA2(CLK_INFRA_I2C1_IMM, CLK_TOP_I2C_SEL, 22),
	GATE_INFRA2(CLK_INFRA_I2C2_ARBITER, CLK_TOP_I2C_SEL, 23),
	GATE_INFRA2(CLK_INFRA_I2C2_IMM, CLK_TOP_I2C_SEL, 24),
	GATE_INFRA2(CLK_INFRA_SPI4, CLK_TOP_SPI_SEL, 25),
	GATE_INFRA2(CLK_INFRA_SPI5, CLK_TOP_SPI_SEL, 26),
	GATE_INFRA2(CLK_INFRA_CQ_DMA, CLK_TOP_AXI_SEL, 27),
	GATE_INFRA2(CLK_INFRA_UFS, CLK_TOP_UFS_SEL, 28),
	GATE_INFRA2(CLK_INFRA_AES_UFSFDE, CLK_TOP_AES_UFSFDE_SEL, 29),
	GATE_INFRA2(CLK_INFRA_UFS_TICK, CLK_TOP_UFS_SEL, 30),
	GATE_INFRA2(CLK_INFRA_SSUSB_XHCI, CLK_TOP_SSUSB_XHCI_SEL, 31),
	/* INFRA3 */
	GATE_INFRA3(CLK_INFRA_MSDC0_SELF, CLK_TOP_MSDC50_0_SEL, 0),
	GATE_INFRA3(CLK_INFRA_MSDC1_SELF, CLK_TOP_MSDC50_0_SEL, 1),
	GATE_INFRA3(CLK_INFRA_MSDC2_SELF, CLK_TOP_MSDC50_0_SEL, 2),
	GATE_INFRA3(CLK_INFRA_UFS_AXI, CLK_TOP_AXI_SEL, 5),
	GATE_INFRA3(CLK_INFRA_I2C6, CLK_TOP_I2C_SEL, 6),
	GATE_INFRA3(CLK_INFRA_AP_MSDC0, CLK_TOP_MSDC50_0_SEL, 7),
	GATE_INFRA3(CLK_INFRA_MD_MSDC0, CLK_TOP_MSDC50_0_SEL, 8),
	GATE_INFRA3(CLK_INFRA_CCIF5_AP, CLK_TOP_AXI_SEL, 9),
	GATE_INFRA3(CLK_INFRA_CCIF5_MD, CLK_TOP_AXI_SEL, 10),
	GATE_INFRA3(CLK_INFRA_PCIE_TOP_H_133M, CLK_TOP_AXI_SEL, 11),
	GATE_INFRA3(CLK_INFRA_FLASHIF_TOP_H_133M, CLK_TOP_AXI_SEL, 14),
	GATE_INFRA3(CLK_INFRA_PCIE_PERI_26M, CLK_TOP_AXI_SEL, 15),
	GATE_INFRA3(CLK_INFRA_CCIF2_AP, CLK_TOP_AXI_SEL, 16),
	GATE_INFRA3(CLK_INFRA_CCIF2_MD, CLK_TOP_AXI_SEL, 17),
	GATE_INFRA3(CLK_INFRA_CCIF3_AP, CLK_TOP_AXI_SEL, 18),
	GATE_INFRA3(CLK_INFRA_CCIF3_MD, CLK_TOP_AXI_SEL, 19),
	GATE_INFRA3(CLK_INFRA_SEJ_F13M, CLK_TOP_CLK26M, 20),
	GATE_INFRA3(CLK_INFRA_AES, CLK_TOP_AXI_SEL, 21),
	GATE_INFRA3(CLK_INFRA_I2C7, CLK_TOP_I2C_SEL, 22),
	GATE_INFRA3(CLK_INFRA_I2C8, CLK_TOP_I2C_SEL, 23),
	GATE_INFRA3(CLK_INFRA_FBIST2FPC, CLK_TOP_MSDC50_0_SEL, 24),
	GATE_INFRA3(CLK_INFRA_DEVICE_APC_SYNC, CLK_TOP_AXI_SEL, 25),
	GATE_INFRA3(CLK_INFRA_DPMAIF_MAIN, CLK_TOP_DPMAIF_MAIN_SEL, 26),
	GATE_INFRA3(CLK_INFRA_PCIE_TL_32K, CLK_TOP_AXI_SEL, 27),
	GATE_INFRA3(CLK_INFRA_CCIF4_AP, CLK_TOP_AXI_SEL, 28),
	GATE_INFRA3(CLK_INFRA_CCIF4_MD, CLK_TOP_AXI_SEL, 29),
	GATE_INFRA3(CLK_INFRA_SPI6, CLK_TOP_SPI_SEL, 30),
	GATE_INFRA3(CLK_INFRA_SPI7, CLK_TOP_SPI_SEL, 31),
	/* INFRA4 */
	GATE_INFRA4(CLK_INFRA_AP_DMA, CLK_INFRA_AP_DMA_PSEUDO, 31),
	/* INFRA5 */
	GATE_INFRA5(CLK_INFRA_133M, CLK_TOP_AXI_SEL, 0),
	GATE_INFRA5(CLK_INFRA_66M, CLK_TOP_AXI_SEL, 1),
	GATE_INFRA5(CLK_INFRA_66M_PERI_BUS, CLK_TOP_AXI_SEL, 2),
	GATE_INFRA5(CLK_INFRA_FREE_DCM_133M, CLK_TOP_AXI_SEL, 3),
	GATE_INFRA5(CLK_INFRA_FREE_DCM_66M, CLK_TOP_AXI_SEL, 4),
	GATE_INFRA5(CLK_INFRA_PERI_BUS_DCM_133M, CLK_TOP_AXI_SEL, 5),
	GATE_INFRA5(CLK_INFRA_PERI_BUS_DCM_66M, CLK_TOP_AXI_SEL, 6),
	GATE_INFRA5(CLK_INFRA_FLASHIF_PERI_26M, CLK_TOP_AXI_SEL, 30),
	GATE_INFRA5(CLK_INFRA_FLASHIF_SFLASH, CLK_TOP_AXI_SEL, 31),
};

static int mt8192_apmixedsys_probe(struct udevice *dev)
{
	return mtk_common_clk_init(dev, &mt8192_clk_tree);
}

static int mt8192_topckgen_probe(struct udevice *dev)
{
	return mtk_common_clk_init(dev, &mt8192_clk_tree);
}

static int mt8192_infracfg_probe(struct udevice *dev)
{
	return mtk_common_clk_gate_init(dev, &mt8192_clk_tree, infra_clks);
}

static const struct udevice_id mt8192_apmixed_compat[] = {
	{ .compatible = "mediatek,mt8192-apmixedsys", },
	{ }
};

static const struct udevice_id mt8192_topckgen_compat[] = {
	{ .compatible = "mediatek,mt8192-topckgen", },
	{ }
};

static const struct udevice_id mt8192_infracfg_compat[] = {
	{ .compatible = "mediatek,mt8192-infracfg", },
	{ }
};

U_BOOT_DRIVER(mtk_clk_apmixedsys) = {
	.name = "mt8192-apmixedsys",
	.id = UCLASS_CLK,
	.of_match = mt8192_apmixed_compat,
	.probe = mt8192_apmixedsys_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_apmixedsys_ops,
	.flags = DM_FLAG_PRE_RELOC,
};

U_BOOT_DRIVER(mtk_clk_topckgen) = {
	.name = "mt8192-topckgen",
  .id = UCLASS_CLK,
	.of_match = mt8192_topckgen_compat,
	.probe = mt8192_topckgen_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_topckgen_ops,
	.flags = DM_FLAG_PRE_RELOC,
};

U_BOOT_DRIVER(mtk_clk_infracfg) = {
	.name = "mt8192-infracfg",
	.id = UCLASS_CLK,
	.of_match = mt8192_infracfg_compat,
	.probe = mt8192_infracfg_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_gate_ops,
	.flags = DM_FLAG_PRE_RELOC,
};
