// SPDX-License-Identifier: GPL-2.0-only
/*
 * MediaTek clock driver for MT8186 SoC, based on Linux.
 *
 * Copyright (c) 2025 Chrultrabook Project
 * Copyright (c) 2022 MediaTek Inc.
 * Author: Alicja Michalska <alicja.michalska@9elements.com>
 * Author: Chun-Jie Chen <chun-jie.chen@mediatek.com>
 */

#include <dm.h>
#include <asm/io.h>
#include <dt-bindings/clock/mt8186-clk.h>
#include <linux/bitops.h>

#include "clk-mtk.h"

/* topckgen */
const struct mtk_fixed_clk top_fixed_clks[] = {
	FIXED_CLK(CLK_TOP_ULPOSC1, 0, 260000000),
	FIXED_CLK(CLK_TOP_466M_FMEM, 0, 533000000),
	FIXED_CLK(CLK_TOP_MPLL, 0, 208000000),
	FIXED_CLK(CLK_TOP_CLK26M, 0, 26000000),
	FIXED_CLK(CLK_TOP_CLK32K, 0, 32000),
	FIXED_CLK(CLK_TOP_CLK13M, 0, 13000000),
};

const struct mtk_fixed_factor top_fixed_divs[] = {
	FACTOR(CLK_TOP_MAINPLL_D2, CLK_APMIXED_MAINPLL, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D2_D2, CLK_TOP_MAINPLL_D2, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D2_D4, CLK_TOP_MAINPLL_D2, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D2_D16, CLK_TOP_MAINPLL_D2, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D3, CLK_APMIXED_MAINPLL, 1, 3, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D3_D2, CLK_TOP_MAINPLL_D3, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D3_D4, CLK_TOP_MAINPLL_D3, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D5, CLK_APMIXED_MAINPLL, 1, 5, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D5_D2, CLK_TOP_MAINPLL_D5, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D5_D4, CLK_TOP_MAINPLL_D5, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D7, CLK_APMIXED_MAINPLL, 1, 7, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MAINPLL_D7_D2, CLK_TOP_MAINPLL_D7, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_MAINPLL_D7_D4, CLK_TOP_MAINPLL_D7, 1, 4, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_UNIVPLL, CLK_APMIXED_UNIV2PLL, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_D2, CLK_APMIXED_UNIV2PLL, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_D2_D2, CLK_TOP_UNIVPLL_D2, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D2_D4, CLK_TOP_UNIVPLL_D2, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D3, CLK_APMIXED_UNIV2PLL, 1, 3, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_D3_D2, CLK_TOP_UNIVPLL_D3, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D3_D4, CLK_TOP_UNIVPLL_D3, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D3_D8, CLK_TOP_UNIVPLL_D3, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D3_D32, CLK_TOP_UNIVPLL_D3, 1, 32, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D5, CLK_APMIXED_UNIV2PLL, 1, 5, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_D5_D2, CLK_TOP_UNIVPLL_D5, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D5_D4, CLK_TOP_UNIVPLL_D5, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_D7, CLK_APMIXED_UNIV2PLL, 1, 7, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_192M, CLK_APMIXED_UNIV2PLL, 1, 13, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_UNIVPLL_192M_D4, CLK_TOP_UNIVPLL_192M, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_192M_D8, CLK_TOP_UNIVPLL_192M, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_192M_D16, CLK_TOP_UNIVPLL_192M, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_UNIVPLL_192M_D32, CLK_TOP_UNIVPLL_192M, 1, 32, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_APLL1_D2, CLK_APMIXED_APLL1, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL1_D4, CLK_APMIXED_APLL1, 1, 4, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL1_D8, CLK_APMIXED_APLL1, 1, 8, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL2_D2, CLK_APMIXED_APLL2, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL2_D4, CLK_APMIXED_APLL2, 1, 4, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_APLL2_D8, CLK_APMIXED_APLL2, 1, 8, CLK_PARENT_APMIXED),

	FACTOR(CLK_TOP_MMPLL_D2, CLK_APMIXED_MMPLL, 1, 2, CLK_PARENT_APMIXED),

	FACTOR(CLK_TOP_TVDPLL_D2, CLK_APMIXED_TVDPLL, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_TVDPLL_D4, CLK_TOP_TVDPLL_D2, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_TVDPLL_D8, CLK_TOP_TVDPLL_D2, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_TVDPLL_D16, CLK_TOP_TVDPLL_D2, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_TVDPLL_D32, CLK_TOP_TVDPLL_D2, 1, 32, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_MSDCPLL, CLK_APMIXED_MSDCPLL, 1, 1, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_MSDCPLL_D2, CLK_TOP_MSDCPLL, 1, 2, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_ULPOSC1_D2, CLK_TOP_ULPOSC1, 1, 2, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_ULPOSC1_D4, CLK_TOP_ULPOSC1, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_ULPOSC1_D8, CLK_TOP_ULPOSC1, 1, 8, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_ULPOSC1_D10, CLK_TOP_ULPOSC1, 1, 10, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_ULPOSC1_D16, CLK_TOP_ULPOSC1, 1, 16, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_ULPOSC1_D32, CLK_TOP_ULPOSC1, 1, 32, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_ADSPPLL_D2, CLK_APMIXED_ADSPPLL, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_ADSPPLL_D4, CLK_TOP_ADSPPLL_D2, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_ADSPPLL_D8, CLK_TOP_ADSPPLL_D2, 1, 8, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_NNAPLL_D2, CLK_APMIXED_NNAPLL, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_NNAPLL_D4, CLK_TOP_NNAPLL_D2, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_NNAPLL_D8, CLK_TOP_NNAPLL_D2, 1, 8, CLK_PARENT_TOPCKGEN),

	FACTOR(CLK_TOP_NNA2PLL_D2, CLK_APMIXED_NNA2PLL, 1, 2, CLK_PARENT_APMIXED),
	FACTOR(CLK_TOP_NNA2PLL_D4, CLK_TOP_NNA2PLL_D2, 1, 4, CLK_PARENT_TOPCKGEN),
	FACTOR(CLK_TOP_NNA2PLL_D8, CLK_TOP_NNA2PLL_D2, 1, 8, CLK_PARENT_TOPCKGEN),

//	FACTOR(CLK_TOP_F_BIST2FPC, 
};

static const int axi_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D7,
	CLK_TOP_MAINPLL_D2_D4,
	CLK_TOP_UNIVPLL_D7
};

static const int scp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D2_D4,
	CLK_TOP_MAINPLL_D5,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_UNIVPLL_D3
};

static const int mfg_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_MAINPLL_D5
};

static const int camtg_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_192M_D8,
	CLK_TOP_UNIVPLL_D3_D8,
	CLK_TOP_UNIVPLL_192M_D4,
	CLK_TOP_UNIVPLL_D3_D32,
	CLK_TOP_UNIVPLL_192M_D16,
	CLK_TOP_UNIVPLL_192M_D32
};

static const int uart_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D3_D8
};

static const int spi_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D4,
	CLK_TOP_MAINPLL_D3_D4,
	CLK_TOP_MAINPLL_D5_D2,
	CLK_TOP_MAINPLL_D2_D4,
	CLK_TOP_MAINPLL_D7,
	CLK_TOP_MAINPLL_D3_D2,
	CLK_TOP_MAINPLL_D5
};

static const int msdc5hclk_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_MAINPLL_D7,
	CLK_TOP_MAINPLL_D3_D2
};

static const int msdc50_0_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MSDCPLL,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_MSDCPLL_D2,
	CLK_TOP_MAINPLL_D7,
	CLK_TOP_MAINPLL_D3_D2,
	CLK_TOP_UNIVPLL_D2_D2
};

static const int msdc30_1_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MSDCPLL_D2,
	CLK_TOP_UNIVPLL_D3_D2,
	CLK_TOP_MAINPLL_D3_D2,
	CLK_TOP_MAINPLL_D7
};

static const int audio_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5_D4,
	CLK_TOP_MAINPLL_D7_D4,
	CLK_TOP_MAINPLL_D2_D16
};

static const int aud_intbus_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D2_D4,
	CLK_TOP_MAINPLL_D7_D2
};

static const int aud_1_parents[] = {
	CLK_TOP_CLK26M,
};

static const int aud_2_parents[] = {
	CLK_TOP_CLK26M,
};

static const int aud_engen1_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL1_D2,
	CLK_TOP_APLL1_D4,
	CLK_TOP_APLL1_D8
};

static const int aud_engen2_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_APLL2_D2,
	CLK_TOP_APLL2_D4,
	CLK_TOP_APLL2_D8
};

static const int disp_pwm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5_D2,
	CLK_TOP_UNIVPLL_D3_D4,
	CLK_TOP_ULPOSC1_D2,
	CLK_TOP_ULPOSC1_D8
};

static const int sspm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_MAINPLL_D3_D2,
	CLK_TOP_MAINPLL_D5,
	CLK_TOP_MAINPLL_D3
};

static const int dxcc_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_MAINPLL_D2_D4
};

static const int usb_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_UNIVPLL_D5_D2
};

static const int srck_parents[] = {
	CLK_TOP_CLK32K,
	CLK_TOP_CLK26M,
	CLK_TOP_ULPOSC1_D10
};

static const int spm_parents[] = {
	CLK_TOP_CLK32K,
	CLK_TOP_ULPOSC1_D10,
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D7_D2
};

static const int i2c_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_UNIVPLL_D3_D4,
	CLK_TOP_UNIVPLL_D5_D2
};

static const int pwm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D3_D8,
	CLK_TOP_UNIVPLL_D3_D4,
	CLK_TOP_UNIVPLL_D2_D4
};

static const int seninf_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D2_D4,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_UNIVPLL_D3_D2
};

static const int aes_msdcfde_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_MAINPLL_D2_D4
};

static const int pwrap_ulposc_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_ULPOSC1_D4,
	CLK_TOP_ULPOSC1_D8,
	CLK_TOP_ULPOSC1_D10,
	CLK_TOP_ULPOSC1_D16,
	CLK_TOP_ULPOSC1_D32
};

static const int camtm_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D2_D4,
	CLK_TOP_UNIVPLL_D3_D2
};

static const int venc_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_MAINPLL_D2,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_MAINPLL_D3,
};

static const int isp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D2,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_MMPLL_D2
};

static const int dpmaif_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_UNIVPLL_D3_D2
};

static const int vdec_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_MAINPLL_D2,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_UNIVPLL_D2_D2
};

static const int disp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D3_D2,
	CLK_TOP_MAINPLL_D5,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_MAINPLL_D2,
};

static const int mdp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D5,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_MAINPLL_D2,
};

static const int audio_h_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D7,
};

static const int ufs_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_MAINPLL_D7,
	CLK_TOP_UNIVPLL_D2_D4,
	CLK_TOP_MAINPLL_D2_D4
};

static const int aes_fde_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_UNIVPLL_D5
};

static const int audiodsp_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_ULPOSC1_D10,
	CLK_TOP_ADSPPLL_D2,
	CLK_TOP_ADSPPLL_D4,
	CLK_TOP_ADSPPLL_D8
};

static const int dvfsrc_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_ULPOSC1_D10,
};

static const int dsi_occ_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D3_D2,
	CLK_TOP_MPLL,
	CLK_TOP_MAINPLL_D5
};

static const int spmi_mst_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_ULPOSC1_D4,
	CLK_TOP_ULPOSC1_D8,
	CLK_TOP_ULPOSC1_D10,
	CLK_TOP_ULPOSC1_D16,
	CLK_TOP_ULPOSC1_D32
};

static const int spinor_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_CLK13M,
	CLK_TOP_MAINPLL_D7_D4,
	CLK_TOP_UNIVPLL_D3_D8,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_MAINPLL_D7_D2
};

static const int nna_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D3_D8,
	CLK_TOP_MAINPLL_D2_D4,
	CLK_TOP_UNIVPLL_D3_D2,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_MAINPLL_D2,
	CLK_TOP_UNIVPLL_D2,
	CLK_TOP_NNAPLL_D2,
	CLK_TOP_NNAPLL_D4,
	CLK_TOP_NNAPLL_D8,
};

static const int nna2_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D3_D8,
	CLK_TOP_MAINPLL_D2_D4,
	CLK_TOP_UNIVPLL_D3_D2,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_MAINPLL_D2,
	CLK_TOP_UNIVPLL_D2,
	CLK_TOP_NNA2PLL_D2,
	CLK_TOP_NNA2PLL_D4,
	CLK_TOP_NNA2PLL_D8,
};

static const int ssusb_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5_D4,
	CLK_TOP_UNIVPLL_D5_D2
};

static const int wpe_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D3_D2,
	CLK_TOP_MAINPLL_D5,
	CLK_TOP_UNIVPLL_D5,
	CLK_TOP_UNIVPLL_D2_D2,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_UNIVPLL_D3,
	CLK_TOP_MAINPLL_D2,
};

static const int dpi_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_TVDPLL_D2,
	CLK_TOP_TVDPLL_D4,
	CLK_TOP_TVDPLL_D8,
	CLK_TOP_TVDPLL_D16,
	CLK_TOP_TVDPLL_D32
};

static const int u3_occ_250m_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_UNIVPLL_D5
};

static const int u3_occ_500m_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_NNA2PLL_D2
};

static const int adsp_bus_parents[] = {
	CLK_TOP_CLK26M,
	CLK_TOP_ULPOSC1_D2,
	CLK_TOP_MAINPLL_D5,
	CLK_TOP_MAINPLL_D2_D2,
	CLK_TOP_MAINPLL_D3,
	CLK_TOP_MAINPLL_D2,
	CLK_TOP_UNIVPLL_D3
};

static const struct mtk_composite top_muxes[] = {
	/* CLK_CFG_0 */
	MUX_GATE(CLK_TOP_AXI, axi_parents, 0x0040, 0, 2, 7),
	MUX_GATE(CLK_TOP_SCP, scp_parents, 0x0040, 8, 3, 15),
	MUX_GATE(CLK_TOP_MFG, mfg_parents, 0x0040, 16, 2, 23),
	MUX_GATE(CLK_TOP_CAMTG, camtg_parents, 0x0040, 24, 3, 31),

	/* CLK_CFG_1 */
	MUX_GATE(CLK_TOP_CAMTG1, camtg_parents, 0x0050, 0, 3, 7),
	MUX_GATE(CLK_TOP_CAMTG2, camtg_parents, 0x0050, 8, 3, 15),
	MUX_GATE(CLK_TOP_CAMTG3, camtg_parents, 0x0050, 16, 3, 23),
	MUX_GATE(CLK_TOP_CAMTG4, camtg_parents, 0x0050, 24, 3, 31),

	/* CLK_CFG_2 */
	MUX_GATE(CLK_TOP_CAMTG5, camtg_parents, 0x0060, 0, 3, 7),
	MUX_GATE(CLK_TOP_CAMTG6, camtg_parents, 0x0060, 8, 3, 15),
	MUX_GATE(CLK_TOP_UART, uart_parents, 0x0060, 16, 1, 23),
	MUX_GATE(CLK_TOP_SPI, spi_parents, 0x0060, 24, 3, 31),

	/* CLK_CFG_3 */
	MUX_GATE(CLK_TOP_MSDC50_0_HCLK, msdc5hclk_parents, 0x0070, 0, 2, 7),
	MUX_GATE(CLK_TOP_MSDC50_0, msdc50_0_parents, 0x0070, 8, 3, 15),
	MUX_GATE(CLK_TOP_MSDC30_1, msdc30_1_parents, 0x0070, 16, 3, 23),
	MUX_GATE(CLK_TOP_AUDIO, audio_parents, 0x0070, 24, 2, 31),

	/* CLK_CFG_4 */
	MUX_GATE(CLK_TOP_AUD_INTBUS, aud_intbus_parents, 0x0080, 0, 2, 7),
	MUX_GATE(CLK_TOP_AUD_1, aud_1_parents, 0x0080, 8, 1, 15),
	MUX_GATE(CLK_TOP_AUD_2, aud_2_parents, 0x0080, 16, 1, 23),
	MUX_GATE(CLK_TOP_AUD_ENGEN1, aud_engen1_parents, 0x0080, 24, 2, 31),

	/* CLK_CFG_5 */
	MUX_GATE(CLK_TOP_AUD_ENGEN2, aud_engen2_parents, 0x0090, 0, 2, 7),
	MUX_GATE(CLK_TOP_DISP_PWM, disp_pwm_parents, 0x0090, 8, 3, 15),
	MUX_GATE(CLK_TOP_SSPM, sspm_parents, 0x0090, 16, 3, 23),
	MUX_GATE(CLK_TOP_DXCC, dxcc_parents, 0x0090, 24, 2, 31),

	/* CLK_CFG_6 */
	MUX_GATE(CLK_TOP_USB_TOP, usb_parents, 0x00a0, 0, 2, 7),
	MUX_GATE(CLK_TOP_SRCK, srck_parents, 0x00a0, 8, 2, 15),
	MUX_GATE(CLK_TOP_SPM, spm_parents, 0x00a0, 16, 2, 23),
	MUX_GATE(CLK_TOP_I2C, i2c_parents, 0x00a0, 24, 2, 31),

	/* CLK_CFG_7 */
	MUX_GATE(CLK_TOP_PWM, pwm_parents, 0x00b0, 0, 2, 7),
	MUX_GATE(CLK_TOP_SENINF, seninf_parents, 0x00b0, 8, 2, 15),
	MUX_GATE(CLK_TOP_SENINF1, seninf_parents, 0x00b0, 16, 2, 23),
	MUX_GATE(CLK_TOP_SENINF2, seninf_parents, 0x00b0, 24, 2, 31),

	/* CLK_CFG_8 */
	MUX_GATE(CLK_TOP_SENINF3, seninf_parents, 0x00c0, 0, 2, 7),
	MUX_GATE(CLK_TOP_AES_MSDCFDE, aes_msdcfde_parents, 0x00c0, 8, 3, 15),
	MUX_GATE(CLK_TOP_PWRAP_ULPOSC, pwrap_ulposc_parents, 0x00c0, 16, 3, 23),
	MUX_GATE(CLK_TOP_CAMTM, camtm_parents, 0x00c0, 24, 2, 31),

	/* CLK_CFG_9 */
	MUX_GATE(CLK_TOP_VENC, venc_parents, 0x00d0, 0, 3, 7),
	MUX_GATE(CLK_TOP_CAM, isp_parents, 0x00d0, 8, 4, 15),
	MUX_GATE(CLK_TOP_IMG1, isp_parents, 0x00d0, 16, 4, 23),
	MUX_GATE(CLK_TOP_IPE, isp_parents, 0x00d0, 24, 4, 31),

	/* CLK_CFG_10 */
	MUX_GATE(CLK_TOP_DPMAIF, dpmaif_parents, 0x00e0, 0, 3, 7),
	MUX_GATE(CLK_TOP_VDEC, vdec_parents, 0x00e0, 8, 3, 15),
	MUX_GATE(CLK_TOP_DISP, disp_parents, 0x00e0, 16, 4, 23),
	MUX_GATE(CLK_TOP_MDP, mdp_parents, 0x00e0, 24, 4, 31),

	/* CLK_CFG_11 */
	MUX_GATE(CLK_TOP_AUDIO_H, audio_h_parents, 0x00ec, 0, 2, 7),
	MUX_GATE(CLK_TOP_UFS, ufs_parents, 0x00ec, 8, 2, 15),
	MUX_GATE(CLK_TOP_AES_FDE, aes_fde_parents, 0x00ec, 16, 2, 23),
	MUX_GATE(CLK_TOP_AUDIODSP, audiodsp_parents, 0x00ec, 24, 3, 31),

	/* CLK_CFG_12 */
	MUX_GATE(CLK_TOP_DVFSRC, dvfsrc_parents, 0x0100, 0, 1, 7),
	MUX_GATE(CLK_TOP_DSI_OCC, dsi_occ_parents, 0x0100, 8, 2, 15),
	MUX_GATE(CLK_TOP_SPMI_MST, spmi_mst_parents, 0x0100, 16, 3, 23),

	/* CLK_CFG_13 */
	MUX_GATE(CLK_TOP_SPINOR, spinor_parents, 0x0110, 0, 3, 6),
	MUX_GATE(CLK_TOP_NNA, nna_parents, 0x0110, 7, 4, 14),
	MUX_GATE(CLK_TOP_NNA1, nna_parents, 0x0110, 15, 4, 22),
	MUX_GATE(CLK_TOP_NNA2, nna2_parents, 0x0110, 23, 4, 30),

	/* CLK_CFG_14 */
	MUX_GATE(CLK_TOP_SSUSB_XHCI, ssusb_parents, 0x0120, 0, 2, 5),
	MUX_GATE(CLK_TOP_SSUSB_TOP_1P, ssusb_parents, 0x0120, 6, 2, 11),
	MUX_GATE(CLK_TOP_SSUSB_XHCI_1P, ssusb_parents, 0x0120, 12, 2, 17),
	MUX_GATE(CLK_TOP_WPE, wpe_parents, 0x0120, 18, 4, 25),

	/* CLK_CFG_15 */
	MUX_GATE(CLK_TOP_DPI, dpi_parents, 0x0180, 0, 3, 6),
	MUX_GATE(CLK_TOP_U3_OCC_250M, u3_occ_250m_parents, 0x0180, 7, 1, 11),
	MUX_GATE(CLK_TOP_U3_OCC_500M, u3_occ_500m_parents, 0x0180, 12, 1, 16),
	MUX_GATE(CLK_TOP_ADSP_BUS, adsp_bus_parents, 0x0180, 17, 3, 23),
};

/* apmixedsys */
#define MT8186_PLL_FMAX		(3800UL * MHZ)
#define MT8186_PLL_FMIN		(1500UL * MHZ)
#define MT8186_INTEGER_BITS	(8)

#define PLL(_id, _reg, _pwr_reg, _en_mask, _flags,		\
		_rst_bar_mask, _pcwbits, _pd_reg, _pd_shift,		\
		_tuner_reg, _tuner_en_reg, _tuner_en_bit,			\
		_pcw_reg, _pcw_shift, _pcw_chg_reg,				\
		_en_reg, _pll_en_bit) {					\
		.id = _id,						\
		.reg = _reg,						\
		.pwr_reg = _pwr_reg,					\
		.en_mask = _en_mask,					\
		.rst_bar_mask = _rst_bar_mask,				\
		.fmax = MT8186_PLL_FMAX,				\
		.fmin = MT8186_PLL_FMIN,				\
		.flags = _flags,					\
		.pcwbits = _pcwbits,					\
		.pcwibits = MT8186_INTEGER_BITS,			\
		.pd_reg = _pd_reg,					\
		.pd_shift = _pd_shift,					\
		.pcw_reg = _pcw_reg,					\
		.pcw_shift = _pcw_shift,				\
		.pcw_chg_reg = _pcw_chg_reg,				\
	}

const struct mtk_pll_data apmixed_plls[] = {
	PLL(CLK_APMIXED_ARMPLL_LL, 0x0204, 0x0210, 0,
		0, 0, 22, 0x0208, 24, 0, 0, 0, 0x0208, 0, 0, 0, 0),
	PLL(CLK_APMIXED_ARMPLL_BL, 0x0214, 0x0220, 0,
		0, 0, 22, 0x0218, 24, 0, 0, 0, 0x0218, 0, 0, 0, 0),
	PLL(CLK_APMIXED_CCIPLL, 0x0224, 0x0230, 0,
		0, 0, 22, 0x0228, 24, 0, 0, 0, 0x0228, 0, 0, 0, 0),
	PLL(CLK_APMIXED_MAINPLL, 0x0244, 0x0250, 0xff000000,
		HAVE_RST_BAR, BIT(23), 22, 0x0248, 24, 0, 0, 0, 0x0248, 0, 0, 0, 0),
	PLL(CLK_APMIXED_UNIV2PLL, 0x0324, 0x0330, 0xff000000,
		HAVE_RST_BAR, BIT(23), 22, 0x0328, 24, 0, 0, 0, 0x0328, 0, 0, 0, 0),
	PLL(CLK_APMIXED_MSDCPLL, 0x038C, 0x0398, 0,
		0, 0, 22, 0x0390, 24, 0, 0, 0, 0x0390, 0, 0, 0, 0),
	PLL(CLK_APMIXED_MMPLL, 0x0254, 0x0260, 0,
		0, 0, 22, 0x0258, 24, 0, 0, 0, 0x0258, 0, 0, 0, 0),
	PLL(CLK_APMIXED_NNAPLL, 0x035C, 0x0368, 0,
		0, 0, 22, 0x0360, 24, 0, 0, 0, 0x0360, 0, 0, 0, 0),
	PLL(CLK_APMIXED_NNA2PLL, 0x036C, 0x0378, 0,
		0, 0, 22, 0x0370, 24, 0, 0, 0, 0x0370, 0, 0, 0, 0),
	PLL(CLK_APMIXED_ADSPPLL, 0x0304, 0x0310, 0,
		0, 0, 22, 0x0308, 24, 0, 0, 0, 0x0308, 0, 0, 0, 0),
	PLL(CLK_APMIXED_MFGPLL, 0x0314, 0x0320, 0,
		0, 0, 22, 0x0318, 24, 0, 0, 0, 0x0318, 0, 0, 0, 0),
	PLL(CLK_APMIXED_TVDPLL, 0x0264, 0x0270, 0,
		0, 0, 22, 0x0268, 24, 0, 0, 0, 0x0268, 0, 0, 0, 0),
	PLL(CLK_APMIXED_APLL1, 0x0334, 0x0344, 0,
		0, 0, 32, 0x0338, 24, 0x0040, 0x000C, 0, 0x033C, 0, 0, 0, 0),
	PLL(CLK_APMIXED_APLL2, 0x0348, 0x0358, 0,
		0, 0, 32, 0x034C, 24, 0x0044, 0x000C, 5, 0x0350, 0, 0, 0, 0),
};

/* infra_ao */
static const struct mtk_gate_regs infra_ao0_cg_regs = {
	.set_ofs = 0x80,
	.clr_ofs = 0x84,
	.sta_ofs = 0x90,
};

static const struct mtk_gate_regs infra_ao1_cg_regs = {
	.set_ofs = 0x88,
	.clr_ofs = 0x8c,
	.sta_ofs = 0x94,
};

static const struct mtk_gate_regs infra_ao2_cg_regs = {
	.set_ofs = 0xa4,
	.clr_ofs = 0xa8,
	.sta_ofs = 0xac,
};

static const struct mtk_gate_regs infra_ao3_cg_regs = {
	.set_ofs = 0xc0,
	.clr_ofs = 0xc4,
	.sta_ofs = 0xc8,
};
                                                              
#define GATE_INFRA_AO0(_id, _parent, _shift)		           \
	GATE_MTK_FLAGS(_id, _parent, &infra_ao0_cg_regs, _shift,\
		CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

#define GATE_INFRA_AO1(_id, _parent, _shift)			\
	GATE_MTK_FLAGS(_id, _parent, &infra_ao1_cg_regs, _shift,\
		CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

#define GATE_INFRA_AO2(_id, _parent, _shift)			\
	GATE_MTK_FLAGS(_id, _parent, &infra_ao2_cg_regs, _shift,\
		CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

#define GATE_INFRA_AO3(_id, _parent, _shift)			\
	GATE_MTK_FLAGS(_id, _parent, &infra_ao3_cg_regs, _shift,\
		CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

static const struct mtk_gate infra_ao_clks[] = {
	/* INFRA_AO0 */
	GATE_INFRA_AO0(CLK_INFRA_AO_PMIC_TMR, CLK_TOP_PWRAP_ULPOSC, 0),
	GATE_INFRA_AO0(CLK_INFRA_AO_PMIC_AP, CLK_TOP_PWRAP_ULPOSC, 1),
	GATE_INFRA_AO0(CLK_INFRA_AO_PMIC_MD, CLK_TOP_PWRAP_ULPOSC, 2),
	GATE_INFRA_AO0(CLK_INFRA_AO_PMIC_CONN, CLK_TOP_PWRAP_ULPOSC, 3),
	GATE_INFRA_AO0(CLK_INFRA_AO_SCP_CORE, CLK_TOP_SCP, 4),
	GATE_INFRA_AO0(CLK_INFRA_AO_SEJ, CLK_TOP_AXI, 5),
	GATE_INFRA_AO0(CLK_INFRA_AO_APXGPT, CLK_TOP_AXI, 6),
	GATE_INFRA_AO0(CLK_INFRA_AO_ICUSB, CLK_TOP_AXI, 8),
	GATE_INFRA_AO0(CLK_INFRA_AO_GCE, CLK_TOP_AXI, 9),
	GATE_INFRA_AO0(CLK_INFRA_AO_THERM, CLK_TOP_AXI, 10),
	GATE_INFRA_AO0(CLK_INFRA_AO_I2C_AP, CLK_TOP_I2C, 11),
	GATE_INFRA_AO0(CLK_INFRA_AO_I2C_CCU, CLK_TOP_I2C, 12),
	GATE_INFRA_AO0(CLK_INFRA_AO_I2C_SSPM, CLK_TOP_I2C, 13),
	GATE_INFRA_AO0(CLK_INFRA_AO_I2C_RSV, CLK_TOP_I2C, 14),
	GATE_INFRA_AO0(CLK_INFRA_AO_PWM_HCLK, CLK_TOP_AXI, 15),
	GATE_INFRA_AO0(CLK_INFRA_AO_PWM1, CLK_TOP_PWM, 16),
	GATE_INFRA_AO0(CLK_INFRA_AO_PWM2, CLK_TOP_PWM, 17),
	GATE_INFRA_AO0(CLK_INFRA_AO_PWM3, CLK_TOP_PWM, 18),
	GATE_INFRA_AO0(CLK_INFRA_AO_PWM4, CLK_TOP_PWM, 19),
	GATE_INFRA_AO0(CLK_INFRA_AO_PWM5, CLK_TOP_PWM, 20),
	GATE_INFRA_AO0(CLK_INFRA_AO_PWM, CLK_TOP_PWM, 21),
	GATE_INFRA_AO0(CLK_INFRA_AO_UART0, CLK_TOP_UART, 22),
	GATE_INFRA_AO0(CLK_INFRA_AO_UART1, CLK_TOP_UART, 23),
	GATE_INFRA_AO0(CLK_INFRA_AO_UART2, CLK_TOP_UART, 24),
	GATE_INFRA_AO0(CLK_INFRA_AO_GCE_26M, CLK_TOP_CLK26M, 27),
	GATE_INFRA_AO0(CLK_INFRA_AO_CQ_DMA_FPC, CLK_TOP_AXI, 28),
	GATE_INFRA_AO0(CLK_INFRA_AO_BTIF, CLK_TOP_AXI, 31),

	/* INFRA_AO1 */
	GATE_INFRA_AO1(CLK_INFRA_AO_SPI0, CLK_TOP_SPI, 1),
	GATE_INFRA_AO1(CLK_INFRA_AO_MSDC0, CLK_TOP_MSDC50_0_HCLK, 2),
	GATE_INFRA_AO1(CLK_INFRA_AO_MSDCFDE,CLK_TOP_AES_MSDCFDE, 3),
	GATE_INFRA_AO1(CLK_INFRA_AO_MSDC1, CLK_TOP_AXI, 4),
	GATE_INFRA_AO1(CLK_INFRA_AO_DVFSRC, CLK_TOP_DVFSRC, 7),
	GATE_INFRA_AO1(CLK_INFRA_AO_GCPU,CLK_TOP_AXI, 8),
	GATE_INFRA_AO1(CLK_INFRA_AO_TRNG, CLK_TOP_AXI, 9),
	GATE_INFRA_AO1(CLK_INFRA_AO_AUXADC, CLK_TOP_CLK26M, 10),
	GATE_INFRA_AO1(CLK_INFRA_AO_CPUM, CLK_TOP_AXI, 11),
	GATE_INFRA_AO1(CLK_INFRA_AO_CCIF1_AP, CLK_TOP_AXI, 12),
	GATE_INFRA_AO1(CLK_INFRA_AO_CCIF1_MD, CLK_TOP_AXI, 13),
	GATE_INFRA_AO1(CLK_INFRA_AO_AUXADC_MD, CLK_TOP_CLK26M, 14),
	GATE_INFRA_AO1(CLK_INFRA_AO_AP_DMA, CLK_TOP_AXI, 18),
	GATE_INFRA_AO1(CLK_INFRA_AO_XIU, CLK_TOP_AXI, 19),
	GATE_INFRA_AO1(CLK_INFRA_AO_DEVICE_APC, CLK_TOP_AXI, 20),
	GATE_INFRA_AO1(CLK_INFRA_AO_CCIF_AP, CLK_TOP_AXI, 23),
	GATE_INFRA_AO1(CLK_INFRA_AO_DEBUGTOP, CLK_TOP_AXI, 24),
	GATE_INFRA_AO1(CLK_INFRA_AO_AUDIO, CLK_TOP_AXI, 25),
	GATE_INFRA_AO1(CLK_INFRA_AO_CCIF_MD, CLK_TOP_AXI, 26),
	GATE_INFRA_AO1(CLK_INFRA_AO_DXCC_SEC_CORE, CLK_TOP_DXCC, 27),
	GATE_INFRA_AO1(CLK_INFRA_AO_DXCC_AO, CLK_TOP_DXCC, 28),
	GATE_INFRA_AO1(CLK_INFRA_AO_IMP_IIC, CLK_TOP_AXI, 29),
	GATE_INFRA_AO1(CLK_INFRA_AO_DRAMC_F26M, CLK_TOP_CLK26M, 31),

	/* INFRA_AO2 */
	GATE_INFRA_AO2(CLK_INFRA_AO_RG_PWM_FBCLK6, CLK_TOP_CLK26M, 0),
	GATE_INFRA_AO2(CLK_INFRA_AO_SSUSB_TOP_HCLK, CLK_TOP_AXI, 1),
	GATE_INFRA_AO2(CLK_INFRA_AO_DISP_PWM, CLK_TOP_DISP_PWM, 2),
	GATE_INFRA_AO2(CLK_INFRA_AO_CLDMA_BCLK, CLK_TOP_AXI, 3),
	GATE_INFRA_AO2(CLK_INFRA_AO_AUDIO_26M_BCLK, CLK_TOP_CLK26M, 4),
	GATE_INFRA_AO2(CLK_INFRA_AO_SSUSB_TOP_P1_HCLK, CLK_TOP_AXI, 5),
	GATE_INFRA_AO2(CLK_INFRA_AO_SPI1, CLK_TOP_SPI, 6),
	GATE_INFRA_AO2(CLK_INFRA_AO_I2C4, CLK_TOP_I2C, 7),
	GATE_INFRA_AO2(CLK_INFRA_AO_MODEM_TEMP_SHARE, CLK_TOP_CLK26M, 8),
	GATE_INFRA_AO2(CLK_INFRA_AO_SPI2, CLK_TOP_SPI, 9),
	GATE_INFRA_AO2(CLK_INFRA_AO_SPI3, CLK_TOP_SPI, 10),
	GATE_INFRA_AO2(CLK_INFRA_AO_SSUSB_TOP_REF, CLK_TOP_CLK26M, 11),
	GATE_INFRA_AO2(CLK_INFRA_AO_SSUSB_TOP_XHCI, CLK_TOP_SSUSB_XHCI, 12),
	GATE_INFRA_AO2(CLK_INFRA_AO_SSUSB_TOP_P1_REF, CLK_TOP_CLK26M, 13),
	GATE_INFRA_AO2(CLK_INFRA_AO_SSUSB_TOP_P1_XHCI, CLK_TOP_SSUSB_XHCI_1P, 14),
	GATE_INFRA_AO2(CLK_INFRA_AO_SSPM, CLK_TOP_SSPM, 15),
	GATE_INFRA_AO2(CLK_INFRA_AO_SSUSB_TOP_P1_SYS, CLK_TOP_SSUSB_TOP_1P, 16),
	GATE_INFRA_AO2(CLK_INFRA_AO_I2C5, CLK_TOP_I2C, 18),
	GATE_INFRA_AO2(CLK_INFRA_AO_I2C5_ARBITER, CLK_TOP_I2C, 19),
	GATE_INFRA_AO2(CLK_INFRA_AO_I2C5_IMM, CLK_TOP_I2C, 20),
	GATE_INFRA_AO2(CLK_INFRA_AO_I2C1_ARBITER, CLK_TOP_I2C, 21),
	GATE_INFRA_AO2(CLK_INFRA_AO_I2C1_IMM, CLK_TOP_I2C, 22),
	GATE_INFRA_AO2(CLK_INFRA_AO_I2C2_ARBITER,  CLK_TOP_I2C, 23),
	GATE_INFRA_AO2(CLK_INFRA_AO_I2C2_IMM, CLK_TOP_I2C, 24),
	GATE_INFRA_AO2(CLK_INFRA_AO_SPI4, CLK_TOP_SPI, 25),
	GATE_INFRA_AO2(CLK_INFRA_AO_SPI5, CLK_TOP_SPI, 26),
	GATE_INFRA_AO2(CLK_INFRA_AO_CQ_DMA, CLK_TOP_AXI, 27),
	GATE_INFRA_AO2(CLK_INFRA_AO_BIST2FPC, CLK_TOP_F_BIST2FPC, 28),

	/* INFRA_AO3 */
	GATE_INFRA_AO3(CLK_INFRA_AO_MSDC0_SELF, CLK_TOP_MSDC50_0, 0),
	GATE_INFRA_AO3(CLK_INFRA_AO_SPINOR, CLK_TOP_SPINOR, 1),
	GATE_INFRA_AO3(CLK_INFRA_AO_SSPM_26M_SELF, CLK_TOP_CLK26M, 3),
	GATE_INFRA_AO3(CLK_INFRA_AO_SSPM_32K_SELF, CLK_TOP_CLK32K, 4),
	GATE_INFRA_AO3(CLK_INFRA_AO_I2C6, CLK_TOP_I2C, 6),
	GATE_INFRA_AO3(CLK_INFRA_AO_AP_MSDC0, CLK_TOP_AXI, 7),
	GATE_INFRA_AO3(CLK_INFRA_AO_MD_MSDC0, CLK_TOP_AXI, 8),
	GATE_INFRA_AO3(CLK_INFRA_AO_MSDC0_SRC, CLK_TOP_MSDC50_0, 9),
	GATE_INFRA_AO3(CLK_INFRA_AO_MSDC1_SRC, CLK_TOP_MSDC30_1, 10),
	GATE_INFRA_AO3(CLK_INFRA_AO_SEJ_F13M, CLK_TOP_CLK26M, 15),
	GATE_INFRA_AO3(CLK_INFRA_AO_AES_TOP0_BCLK, CLK_TOP_AXI, 16),
	GATE_INFRA_AO3(CLK_INFRA_AO_MCU_PM_BCLK, CLK_TOP_AXI, 17),
	GATE_INFRA_AO3(CLK_INFRA_AO_CCIF2_AP, CLK_TOP_AXI, 18),
	GATE_INFRA_AO3(CLK_INFRA_AO_CCIF2_MD, CLK_TOP_AXI, 19),
	GATE_INFRA_AO3(CLK_INFRA_AO_CCIF3_AP, CLK_TOP_AXI, 20),
	GATE_INFRA_AO3(CLK_INFRA_AO_CCIF3_MD, CLK_TOP_AXI, 21),
	GATE_INFRA_AO3(CLK_INFRA_AO_FADSP_26M, CLK_TOP_CLK26M, 22),
	GATE_INFRA_AO3(CLK_INFRA_AO_FADSP_32K, CLK_TOP_CLK32K, 23),
	GATE_INFRA_AO3(CLK_INFRA_AO_CCIF4_AP, CLK_TOP_AXI, 24),
	GATE_INFRA_AO3(CLK_INFRA_AO_CCIF4_MD, CLK_TOP_AXI, 25),
	GATE_INFRA_AO3(CLK_INFRA_AO_FADSP, CLK_TOP_AUDIODSP, 27),
	GATE_INFRA_AO3(CLK_INFRA_AO_FLASHIF_133M, CLK_TOP_AXI, 28),
	GATE_INFRA_AO3(CLK_INFRA_AO_FLASHIF_66M, CLK_TOP_AXI, 29),
};

static const struct mtk_clk_tree mt8186_clk_tree = {
	.xtal_rate = 26 * MHZ,
	.xtal2_rate = 26 * MHZ,
	.fdivs_offs = CLK_TOP_MAINPLL_D2,
	.muxes_offs = CLK_TOP_AXI,
	.plls = apmixed_plls,
	.fclks = top_fixed_clks,
	.fdivs = top_fixed_divs,
	.muxes = top_muxes,
};

/* binding code */
static int mt8186_topckgen_probe(struct udevice *dev)
{
	return mtk_common_clk_init(dev, &mt8186_clk_tree);
}

static int mt8186_apmixedsys_probe(struct udevice *dev)
{
	return mtk_common_clk_init(dev, &mt8186_clk_tree);
}

static int mt8186_infracfg_ao_probe(struct udevice *dev)
{
	return mtk_common_clk_gate_init(dev, &mt8186_clk_tree, infra_ao_clks);
}

static const struct udevice_id mt8186_topckgen_compat[] = {
	{ .compatible = "mediatek,mt8186-topckgen", },
	{ }
};

static const struct udevice_id mt8186_apmixedsys_compat[] = {
	{ .compatible = "mediatek,mt8186-apmixedsys", },
	{ }
};

static const struct udevice_id mt8186_infracfg_ao_compat[] = {
	{ .compatible = "mediatek,mt8186-infracfg_ao", },
	{ }
};

U_BOOT_DRIVER(mtk_clk_topckgen) = {
	.name = "mt8186-topckgen",
	.id = UCLASS_CLK,
	.of_match = mt8186_topckgen_compat,
	.probe = mt8186_topckgen_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_topckgen_ops,
	.flags = DM_FLAG_PRE_RELOC,
};

U_BOOT_DRIVER(mtk_clk_apmixedsys) = {
	.name = "mt8186-apmixedsys",
	.id = UCLASS_CLK,
	.of_match = mt8186_apmixedsys_compat,
	.probe = mt8186_apmixedsys_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_apmixedsys_ops,
	.flags = DM_FLAG_PRE_RELOC,
};

U_BOOT_DRIVER(mtk_clk_infracfg_ao) = {
	.name = "mt8186-infracfg_ao",
	.id = UCLASS_CLK,
	.of_match = mt8186_infracfg_ao_compat,
	.probe = mt8186_infracfg_ao_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_gate_ops,
	.flags = DM_FLAG_PRE_RELOC,
};
